server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fcl?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    threads:
      virtual:
        enabled: true

